# Generated by Django 4.2.7 on 2024-08-03 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2024, 8, 3, 15, 20, 1, 758963, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
