# Generated by Django 4.2.7 on 2024-08-03 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otps',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 3, 15, 25, 41, 628746, tzinfo=datetime.timezone.utc)),
        ),
    ]
